### ISSUE TITLE
Call of outputSetting with errorColor doesn't works

### ISSUE THREAD

**Issue by FrankTheCat** [HuddleEng/Resemble.js#138]
Hi,
I really like your plugin and use it on a project. Continue your good works.

Fix in resemble.js:
Line 721 remove if (options.hasOwnProperty(key)) {
Line 726 remove }

Without this fix it required to call outputSettings like this to works:
resembleControl.outputSettings({
	errorColor: {
		red: 255,
		green: 0,
		blue: 0						
	},
	red: 255,
	green: 0,
	blue: 0							
}).repaint();

Thanks

**Comment by jamescryer** [comment]
Thanks, I've added a test, and fixed the issue.
