### ISSUE TITLE
Visual Automation: which one to select

### ISSUE THREAD

**Issue by AmitKulkarni9** [HuddleEng/Resemble.js#139]
I am looking to do Visual Automation for one of the website. Confused which one to use. 
https://github.com/HuddleEng/PhantomCSS -- Not maintained anymore
https://github.com/HuddleEng/Resemble.js

Is this project replacement for https://github.com/HuddleEng/PhantomCSS ? 

Thanks,
Amit

**Comment by jamescryer** [comment]
Resemble.js is a library for comparing any two images (jpeg, png, svg, bmp...), it's not a visual testing tool though you can build your own visual testing tool with it. 

PhantomCSS is a visual testing tool for websites. In combination with SlimerJS, PhantomCSS is still a useful tool for testing modern websites.

For visual testing PhantomCSS is still an option (though unsupported).  Other tools exist too, such as https://github.com/americanexpress/jest-image-snapshot
