### ISSUE TITLE
Comparing Two Data URI Images in the Browser

### ISSUE THREAD

**Issue by tomgallagher** [HuddleEng/Resemble.js#144]
Hi

Nothing immediately obvious in the docs about this. Would I pass in the data URI string e.g. "data:image/gif;base64,R0lGODlhyAAiALM...DfD0QAADs=" or would I create an Image element with the data URI as src and pass each of those in?

Thanks. Great project!

Tom

**Comment by jamescryer** [comment]
Yes, just pass the data URI string, as seen here https://github.com/HuddleEng/Resemble.js/blob/master/chai-tests/main_spec.js#L38.  I'll add a note to the README.

**Comment by tomgallagher** [comment]
Thanks for getting back.

**Comment by tomgallagher** [comment]
Just a note on your additions to the README

Getting warning:

> warning resemble.outputSettings mutates global state, and will be removed in 3.0.0

Any other way I should be doing it?

**Comment by jamescryer** [comment]
Sorry for the late reply.  Not right now, the warning is unhelpful given that it would not be changed before the next major release.  Another release is not currently planned.

**Comment by Kartikeya99** [comment]
Has this been resolved? Because I'm using the 3.0.0 version and still get this warning.

**Comment by jamescryer** [comment]
@Kartikeya99 the warning remains. There isn't much need to break backward compatibility right now.

**Comment by Kartikeya99** [comment]
Is there a workaround for this?

**Comment by jamescryer** [comment]
@Kartikeya99 It's just a warning message so hopefully you don't need a workaround, is it causing a bug of some kind? 

The message is just there to let users know that all subsequent calls to Resemble will be effected by the settings changes.

Maybe this warning might be better in the README rather than logged, if you'd like to create a pull request removing the logged warning I'll be happy to review.

**Comment by Kartikeya99** [comment]
@jamescryer I'll make the pull request removing the warning and changing the readme shortly.

**Comment by Kartikeya99** [comment]
@jamescryer I've made the PR https://github.com/rsmbl/Resemble.js/pull/182 please review. The travis CI is failing with `The command "npm run test:codacy-coverage" exited with 1.` but my codacy coverage is passing. Please tell me where I can fix this. Thanks.
